/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UJhWUiS3GM5
 */
import Image from "next/image"
import Link from "next/link"

export function Main() {
  return (
    <section className="flex flex-col items-center justify-start
     min-h-screen bg-white">
      {/* <Image
        alt="Logo"
        className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
        height="70"
        src="/BIM-primary-logo-1.png"
        width="500"
      /> */}
      {/* <p className="text-center text-zinc-500 w-1/2 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-zinc-400 mb-12">
        We are excited to announce that Maine Feldenkrais & Physical Therapy has joined the Back in Motion Physical Therapy family. This partnership will allow us to expand our services and better serve our community. <br/><br/>

The physical therapists at Back in Motion Physical Therapy have advanced training in a variety of areas, so we can help you with even the most complex musculoskeletal injuries. Whether you’re getting back to work, playing sports, or simply trying to complete everyday activities, we can help you reach your full potential. <br/><br/>

For our existing patients, nothing will change. You will still be able to visit the same clinic and work with the same physical therapists. <br/><br/>

We are very grateful for your trust and support, and we look forward to continuing to serve you as part of the Back in Motion Physical Therapy family. 
      </p> */}
      <Link
        className="inline-flex h-10 items-center justify-center rounded-md bg-cyan-900 px-16 py-8 text-xl font-medium text-zinc-50 shadow transition-colors hover:bg-zinc-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-zinc-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-cyan-900 dark:hover:bg-cyan-900 dark:focus-visible:ring-zinc-300"
        href="https://armorpt.com/location/physical-therapy-battle-creek-lakeview-mi/"
      >
        Continue to Armor Physical Therapy - Battle Creek Lakeview
      </Link>
    </section>
  )
}
